version: 'latest'

services:
  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=ricardo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
volumes:
  postgres-volume:
    external: true